export const GET_VIDEOS = 'GET_VIDEOS';
export const GET_VIDEOS_BY_TITLE = 'GET_VIDEOS_BY_TITLE';
export const ADD_VIDEO = 'ADD_VIDEO';
export const DELETE_VIDEO = 'DELETE_VIDEO';
export const UPDATE_VIDEO_CLUSTER = 'UPDATE_VIDEO_CLUSTER';
// export const REMOVE_VIDEO_CLUSTER = 'REMOVE_VIDEO_CLUSTER';
export const VIDEOS_LOADING = 'VIDEOS_LOADING';